name: atvavrupa

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gereklilikleri Yükle
        run: |
          pip install --no-cache-dir streamlink requests -qq

      - name: Python Scriptini Çalıştır
        run: python3 atvavrupa.py

      - name: Değişiklikleri GitHub'a Gönder
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add streams/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto sync streams: $(date +'%Y-%m-%d %H:%M:%S')" && git push)
