name: atvavrupa

on:
  schedule:
    - cron: '*/10 * * * *' # Her 10 dakikada bir çalışır
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies & Streamlink
        run: |
          python -m pip install --upgrade pip
          pip install streamlink requests

      - name: Execute Python script
        run: |       
          python3 atvavrupa.py 

      - name: Commit & Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add streams/
          git commit -m "Stream updated $(date +'%Y-%m-%d %H:%M:%S') [skip ci]" || echo "No changes to commit"
          git push
