name: Turkuvaz M3U8 Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # TS linklerinin tazeliğini korumak için her 15 dakikada bir çalışır

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          playwright install chromium

      - name: Run Script
        run: |
          python trkvz_segment.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.m3u8
          git commit -m "Auto-update m3u8 playlists [skip ci]" || echo "No changes to commit"
          git push
